#define CMD_CLEAR_ALL_BREAKPOINTS        1
#define CMD_END_OF_FILE                  2
#define CMD_CLEARALLBREAKPOINT_PARAM_FULLFILEPATH   3
#define CMD_CLEARALLBREAKPOINT_PARAM_DOUBLEQUOTE   4
#define CMD_CATCH                        5
#define CMD_CATCH_THROW                  6
#define CMD_SET                          7
#define CMD_SET_CONFIRM                  8
#define CMD_SET_OFF                      9
#define CMD_SET_WIDTH                   10
#define CMD_SET_NUMERIC                 11
#define CMD_SET_HEIGHT                  12
#define CMD_SET_BREAKPOINT              13
#define CMD_SET_PENDING                 14
#define CMD_SET_ON                      15
#define CMD_SET_PRINT                   16
#define CMD_SET_ASM_DEMANGLE            17
#define CMD_SET_ELEMENTS                18
#define CMD_SET_UNWINDONSIGNAL          19
#define CMD_SET_DISASSEMBLY_FLAVOR      20
#define CMD_SET_ATT                     21
#define CMD_SET_PROMPT                  22
#define CMD_SET_PROMPT_STRING           23
#define CMD_OUTPUT                      24
#define CMD_OUTPUT_VARIABLE_NAME        25
#define CMD_WHATIS                      26
#define CMD_WHATIS_VARIABLE_NAME        27
#define CMD_QUIT                        28
#define CMD_DUMMY                       29
#define CMD_NEXT                        30
#define CMD_FINISH                      31
#define CMD_STEP                        32
#define CMD_DELETE                      33
#define CMD_DELETE_PARAM_BREAKPOINTS    34
#define CMD_DELETE_PARAM_NUMERIC        35
#define CMD_BREAK                       36
#define CMD_BREAK_PARAM_FULLFILEPATH    37
#define CMD_BREAK_PARAM_DOUBLEQUOTE     38
#define CMD_TBREAK                      39
#define CMD_TBREAK_PARAM_FULLFILEPATH   40
#define CMD_TBREAK_PARAM_DOUBLEQUOTE    41
#define CMD_SOURCE                      42
#define CMD_SOURCE_PARAM_FULLFILEPATH   43
#define CMD_CONTINUE                    44
#define CMD_FRAME                       45
#define CMD_FRAME_PARAM_FRAMENO         46
#define CMD_BACKTRACE                   47
#define CMD_BACKTRACE_PARAM_FRAMECOUNT  48
#define CMD_BACKTRACE_PARAM_OTHERS      49
#define CMD_ATTACH                      50
#define CMD_ATTACH_PARAM_SESSION_ID     51
#define CMD_DETACH                      52
#define CMD_KILL                        53
#define CMD_INFO                        54
#define CMD_INFO_PARAM_LOCALS           55
#define CMD_INFO_PARAM_ARGS             56
#define CMD_INFO_PARAM_GLOBALS          57
#define CMD_INFO_PARAM_FRAME            58
#define CMD_SHOW                        59
#define CMD_SHOW_PARAM_SESSION_COUNT    60
#define CMD_SHOW_PARAM_VERSION          61
#define CMD_EXIT                        62
#define CMD_ANY_CHARACTER               63
#define CMD_EXECUTE                     64
#define CMD_SEMI_COLON                  65
